# Generated by Django 6.0 on 2026-01-27 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car_inventory',
            old_name='car_count',
            new_name='cars_count',
        ),
        migrations.RenameField(
            model_name='car_inventory',
            old_name='car_value',
            new_name='cars_value',
        ),
    ]
