# Generated by Django 6.0 on 2026-02-14 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_car_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, default='cars/img-indisponivel.jpg', null=True, upload_to='cars/'),
        ),
    ]
